name: sfa

services:
  sfa:
    container_name: sfa
    image: iita/sfa
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8501:8501
    environment:
      GOOGLE_APPLICATION_CREDENTIALS_TEST: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
#      - ./SFapp.py:/SFApp/SFapp.py
      #      - ./eefun.py:/SFApp/eefun.py
      - ./secrets/midyear-button-379815-391083128e1a.json:/var/secrets/google/midyear-button-379815-391083128e1a.json

networks:
  default:
    name: sfa