name: sfa

services:
  sfa:
    container_name: sfa
    image: iita/sf-app:${VERSION_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8501:8501
    environment:
      #GOOGLE_APPLICATION_CREDENTIALS_TEST: ${GOOGLE_APPLICATION_CREDENTIALS}
      AUTH_MECHANISM: ${AUTH_MECHANISM}
    volumes:
      - ~/secrets/sampling-frames-iita-a80b3e765388.json:/var/secrets/google/sampling-frames-iita-a80b3e765388.json

networks:
  default:
    name: sfa
